# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  REVIEW: Review successful

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  review:
    cmds:
      - echo "{{.REVIEW}}"
    silent: true
